[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"

[dev]
  command = "npm start"
  targetPort = 3000
  port = 8888
  autoLaunch = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
